package dev.doole.corecrucible;

import dev.doole.corecrucible.client.LauncherClient;
import dev.doole.corecrucible.client.RodClient;
//? if <1.21.2 {
/*import dev.doole.corecrucible.client.TieredShieldRenderer;
*///?}
import dev.doole.corecrucible.registry.ModDispensers;
import net.minecraft.resources.Identifier;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.spongepowered.asm.mixin.MixinEnvironment;

/**
 * The mod's shared entry point. Both loaders call {@link #onInitialize()} on the server and
 * {@link #onInitializeClient()} on the client; everything else (registries, events, mixins) hooks in from there.
 *
 * <p>Where things live:
 * <ul>
 *   <li>{@code registry/}: items, tiers and every stat table. The numbers there are defaults; players override them in
 *       {@code config/dooles_core_crucible.json} (see {@code config/BalanceConfig}).</li>
 *   <li>{@code recipe/}: the smithing upgrade and alloy recipes. The recipe JSON itself is generated.</li>
 *   <li>{@code gameplay/}, {@code item/}, {@code enchant/}, {@code worldgen/}: how the gear, enchantments and ore
 *       veins behave.</li>
 *   <li>{@code client/}: tooltip, recipe book and item rendering. {@code compat/jei/}: the optional JEI plugin.</li>
 *   <li>{@code mixin/}: changes to vanilla code. {@code platform/}: the Fabric and NeoForge entry points.</li>
 *   <li>Recipes, lang, tags, models and advancements under {@code src/main/resources} are generated by
 *       {@code tools/gen_data.py}, and textures by {@code tools/gen_textures.py}: edit the scripts, not the output.</li>
 *   <li>Enchantment definitions: {@code data/dooles_core_crucible/enchantment/*.json}.</li>
 * </ul>
 *
 * <p>Reading the code:
 * <ul>
 *   <li>Lines starting {@code //?} are Stonecutter markers. Code between {@code //? if >=1.21.2} and {@code //?} else}
 *       is for 26.x, the else branch for 1.21.1. The branch that isn't being built is kept inside a comment.</li>
 *   <li>Mixins change vanilla methods. {@code @Inject} runs our code at a point in a method (HEAD = start, RETURN or
 *       TAIL = end), {@code @WrapOperation} wraps one call inside a method, {@code @ModifyReturnValue} changes what a
 *       method returns, and {@code @Accessor} / {@code @Invoker} give access to private fields and methods.</li>
 *   <li>Anything added to a vanilla class is prefixed {@code dooles_core_crucible$} so it can't clash with other mods.</li>
 *   <li>"Tier" means a step in the chain (Wood to Reinforced, {@code registry/ModTiers}); "type" or "slot" means the
 *       kind of gear (pickaxe, helmet, bow..., {@code registry/EquipType}).</li>
 * </ul>
 */
public class CoreCrucible {

    public static final String MOD_ID = /*$ mod_id*/ "dooles_core_crucible";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    public static void onInitialize() {
        LOGGER.info("Doole's Core & Crucible initialising");
        ModDispensers.register();
        // For testing: -Ddooles_core_crucible.debug.audit=true (gradle -PmixinAudit=true) applies every mixin now.
        if (Boolean.getBoolean("dooles_core_crucible.debug.audit")) {
            MixinEnvironment.getCurrentEnvironment().audit();
            LOGGER.info("Doole's Core & Crucible mixin audit finished");
        }
    }

    public static void onInitializeClient() {
        LauncherClient.registerItemProperties();
        RodClient.registerItemProperties();
        //? if <1.21.2 {
        /*TieredShieldRenderer.registerItemProperties();
        *///?}
    }

    /** Shorthand for building one of this mod's resource locations, e.g. {@code dooles_core_crucible:iron_ingot}. */
    public static Identifier id(String path) {
        return Identifier.fromNamespaceAndPath(MOD_ID, path);
    }
}
