package dev.doole.corecrucible.client;

import com.mojang.blaze3d.platform.InputConstants;
import dev.doole.corecrucible.CoreCrucible;
import dev.doole.corecrucible.enchant.VeinMining;
import dev.doole.corecrucible.enchant.VeinMining.ModePayload;
import dev.doole.corecrucible.enchant.VeinShape;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.ChatFormatting;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;
import net.minecraft.world.phys.shapes.BooleanOp;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/**
 * Client half of Vein Resonance, ported from Applied-Enchantments: holding the Vein Resonance key
 * (` by default) shows a shape menu, the mouse wheel picks a shape, and the block outline grows to cover every
 * block the next break would take. Hooks: {@code MinecraftMixin} (tick), {@code MouseHandlerMixin} (scroll),
 * {@code HudMixin} (menu), {@code BlockOutlineMixin} (outline); the key is registered per loader.
 */
public final class VeinMiningClient {
    // Lang key prefixes. The text itself lives in assets/dooles_core_crucible/lang/en_us.json (generated by gen_data.py).
    private static final String KEY = "key." + CoreCrucible.MOD_ID + ".vein_mine";
    private static final String HUD = "hud." + CoreCrucible.MOD_ID + ".vein.";
    // The key players hold for vein mining. Default: the ` (grave) key; can be rebound in Controls.
    //? if >=1.21.2 {
    public static final KeyMapping VEIN_KEY = new KeyMapping(KEY, InputConstants.KEY_GRAVE, KeyMapping.Category.GAMEPLAY);
    //?} else {
    /*public static final KeyMapping VEIN_KEY = new KeyMapping(KEY, InputConstants.KEY_GRAVE, KeyMapping.CATEGORY_GAMEPLAY);
    *///?}

    /** Index into {@link VeinShape#values()}; kept across tools. */
    private static int selected;
    // lastSent: what the server was last told, so a message is only sent when something changes.
    // previewOrigin / previewBlocks / previewShape: the block being looked at, the extra blocks that would break, and the
    // outline drawn around all of them.
    private static ModePayload lastSent;

    private static BlockPos previewOrigin;
    private static List<BlockPos> previewBlocks = List.of();
    private static VoxelShape previewShape;

    private VeinMiningClient() {
    }

    private static boolean keyHeld(Minecraft minecraft) {
        return minecraft.player != null && ClientCompat.screen(minecraft) == null && VEIN_KEY.isDown();
    }

    /** Vein Resonance level of the held tool, or 0. */
    private static int heldLevel(Minecraft minecraft) {
        LocalPlayer player = minecraft.player;
        return player == null ? 0 : VeinMining.level(player.level(), player.getMainHandItem());
    }

    // Every client tick: tell the server if the key or shape changed, then refresh the outline preview.
    public static void tick(Minecraft minecraft) {
        if (minecraft.player == null || minecraft.getConnection() == null) {
            lastSent = null;
            clearPreview();
            return;
        }
        boolean active = keyHeld(minecraft);
        ModePayload mode = new ModePayload(active, selected);
        if (!mode.equals(lastSent)) {
            minecraft.getConnection().send(new ServerboundCustomPayloadPacket(mode));
            lastSent = mode;
        }
        updatePreview(minecraft, active);
    }

    /** Mouse wheel while the key is held picks a shape; returns true when the scroll was used. */
    public static boolean scroll(double amountY) {
        Minecraft minecraft = Minecraft.getInstance();
        int level = heldLevel(minecraft);
        if (amountY == 0.0 || level <= 0 || !keyHeld(minecraft)) return false;
        List<VeinShape> unlocked = VeinShape.unlocked(level);
        int index = unlocked.indexOf(VeinShape.effective(selected, level));
        // Scroll up moves up the menu, scroll down moves down; it wraps round at either end, skipping locked shapes.
        int step = amountY > 0.0 ? -1 : 1;
        selected = unlocked.get(Math.floorMod(index + step, unlocked.size())).ordinal();
        return true;
    }

    // ---- Preview outline ------------------------------------------------------------------------------------

    private static void updatePreview(Minecraft minecraft, boolean active) {
        LocalPlayer player = minecraft.player;
        int level = heldLevel(minecraft);
        if (!active || level <= 0 || player == null || minecraft.level == null
                || !(minecraft.hitResult instanceof BlockHitResult hit) || hit.getType() != HitResult.Type.BLOCK) {
            clearPreview();
            return;
        }
        BlockPos origin = hit.getBlockPos();
        BlockState state = minecraft.level.getBlockState(origin);
        ItemStack tool = player.getMainHandItem();
        // The same plan() the server uses, so the preview matches what will actually break.
        List<BlockPos> blocks = VeinMining.plan(minecraft.level, player, origin, state, hit.getDirection(), tool, level,
                VeinShape.effective(selected, level));
        if (blocks.isEmpty() && !player.hasCorrectToolForDrops(state)) {
            clearPreview();
            return;
        }
        if (origin.equals(previewOrigin) && blocks.equals(previewBlocks)) return;
        previewOrigin = origin;
        previewBlocks = blocks;
        // One merged shape, so the outline follows the edge of the whole area instead of boxing every block.
        VoxelShape shape = Shapes.block();
        for (BlockPos pos : blocks) {
            shape = Shapes.joinUnoptimized(shape, Shapes.block().move(pos.getX() - origin.getX(), pos.getY() - origin.getY(),
                    pos.getZ() - origin.getZ()), BooleanOp.OR);
        }
        previewShape = shape.optimize();
    }

    private static void clearPreview() {
        previewOrigin = null;
        previewBlocks = List.of();
        previewShape = null;
    }

    /** The shape vanilla should outline for the targeted block: the whole vein while previewing. */
    public static VoxelShape outlineShape(VoxelShape original) {
        Minecraft minecraft = Minecraft.getInstance();
        if (previewShape != null && minecraft.hitResult instanceof BlockHitResult hit && hit.getBlockPos().equals(previewOrigin)) {
            return previewShape;
        }
        return original;
    }

    // ---- Shape menu -----------------------------------------------------------------------------------------

    /** Lines of the shape menu, or empty when it's hidden. */
    public static List<Component> menuLines() {
        Minecraft minecraft = Minecraft.getInstance();
        int level = heldLevel(minecraft);
        if (level <= 0 || !keyHeld(minecraft)) return List.of();
        VeinShape current = VeinShape.effective(selected, level);

        List<Component> lines = new ArrayList<>();
        int count = previewOrigin == null ? 0 : previewBlocks.size() + 1;
        lines.add(Component.translatable(HUD + "title", count).withStyle(ChatFormatting.GOLD));
        for (VeinShape shape : VeinShape.values()) {
            Component name = Component.translatable(shape.translationKey());
            if (!shape.isUnlocked(level)) {
                lines.add(Component.translatable(HUD + "locked", name, Component.translatable("enchantment.level." + shape.requiredLevel()))
                        .withStyle(ChatFormatting.DARK_GRAY));
            } else if (shape == current) {
                lines.add(Component.literal("> ").append(name).withStyle(ChatFormatting.YELLOW));
            } else {
                lines.add(Component.literal("  ").append(name).withStyle(ChatFormatting.GRAY));
            }
        }
        lines.add(Component.translatable(HUD + "scroll").withStyle(ChatFormatting.DARK_GRAY));
        return lines;
    }
}
