package dev.doole.corecrucible.client;

import com.mojang.blaze3d.platform.InputConstants;
import dev.doole.corecrucible.CoreCrucible;
import dev.doole.corecrucible.enchant.VeinMining;
import dev.doole.corecrucible.enchant.VeinMining.ModePayload;
import dev.doole.corecrucible.enchant.VeinShape;
import java.util.List;
import net.minecraft.ChatFormatting;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.core.BlockPos;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.HitResult;

/**
 * Client half of Vein Resonance, ported from Applied-Enchantments: holding the Vein Resonance key
 * (Left Alt by default) shows a shape selector under the crosshair, the mouse wheel picks a shape, and every block the next
 * break would take gives off purple resonance motes. Hooks: {@code MinecraftMixin} (tick), {@code MouseHandlerMixin}
 * (scroll), {@code HudMixin} (selector); the key is registered per loader.
 */
public final class VeinMiningClient {
    // Lang key prefixes. The text itself lives in assets/dooles_core_crucible/lang/en_us.json (generated by gen_data.py).
    private static final String KEY = "key." + CoreCrucible.MOD_ID + ".vein_mine";
    private static final String HUD = "hud." + CoreCrucible.MOD_ID + ".vein.";
    // The key players hold for vein mining. Default: Left Alt; can be rebound in Controls.
    //? if >=1.21.2 {
    public static final KeyMapping VEIN_KEY = new KeyMapping(KEY, InputConstants.KEY_LALT, KeyMapping.Category.GAMEPLAY);
    //?} else {
    /*public static final KeyMapping VEIN_KEY = new KeyMapping(KEY, InputConstants.KEY_LALT, KeyMapping.CATEGORY_GAMEPLAY);
    *///?}

    /** Index into {@link VeinShape#values()}; kept across tools. */
    private static int selected;
    // lastSent: what the server was last told, so a message is only sent when something changes.
    // previewOrigin / previewBlocks: the block being looked at and the extra blocks that would break with it.
    private static ModePayload lastSent;

    private static BlockPos previewOrigin;
    private static List<BlockPos> previewBlocks = List.of();

    private VeinMiningClient() {
    }

    private static boolean keyHeld(Minecraft minecraft) {
        return minecraft.player != null && ClientCompat.screen(minecraft) == null && VEIN_KEY.isDown();
    }

    /** Vein Resonance level of the held tool, or 0. */
    private static int heldLevel(Minecraft minecraft) {
        LocalPlayer player = minecraft.player;
        return player == null ? 0 : VeinMining.level(player.level(), player.getMainHandItem());
    }

    // Every client tick: tell the server if the key or shape changed, then refresh the outline preview.
    public static void tick(Minecraft minecraft) {
        if (minecraft.player == null || minecraft.getConnection() == null) {
            lastSent = null;
            clearPreview();
            return;
        }
        boolean active = keyHeld(minecraft);
        ModePayload mode = new ModePayload(active, selected);
        if (!mode.equals(lastSent)) {
            minecraft.getConnection().send(new ServerboundCustomPayloadPacket(mode));
            lastSent = mode;
        }
        updatePreview(minecraft, active);
    }

    /** Mouse wheel while the key is held picks a shape; returns true when the scroll was used. */
    public static boolean scroll(double amountY) {
        Minecraft minecraft = Minecraft.getInstance();
        int level = heldLevel(minecraft);
        if (amountY == 0.0 || level <= 0 || !keyHeld(minecraft)) return false;
        List<VeinShape> unlocked = VeinShape.unlocked(level);
        int index = unlocked.indexOf(VeinShape.effective(selected, level));
        // Scroll up moves up the menu, scroll down moves down; it wraps round at either end, skipping locked shapes.
        int step = amountY > 0.0 ? -1 : 1;
        selected = unlocked.get(Math.floorMod(index + step, unlocked.size())).ordinal();
        return true;
    }

    // ---- Preview -------------------------------------------------------------------------------------------

    private static void updatePreview(Minecraft minecraft, boolean active) {
        LocalPlayer player = minecraft.player;
        int level = heldLevel(minecraft);
        if (!active || level <= 0 || player == null || minecraft.level == null
                || !(minecraft.hitResult instanceof BlockHitResult hit) || hit.getType() != HitResult.Type.BLOCK) {
            clearPreview();
            return;
        }
        BlockPos origin = hit.getBlockPos();
        BlockState state = minecraft.level.getBlockState(origin);
        ItemStack tool = player.getMainHandItem();
        // The same plan() the server uses, so the preview matches what will actually break.
        List<BlockPos> blocks = VeinMining.plan(minecraft.level, player, origin, state, hit.getDirection(), tool, level,
                VeinShape.effective(selected, level));
        if (blocks.isEmpty() && !player.hasCorrectToolForDrops(state)) {
            clearPreview();
            return;
        }
        previewOrigin = origin;
        previewBlocks = blocks;
        // Every few ticks, each block that would break gives off a resonance mote somewhere on or just outside it.
        if (player.tickCount % 3 == 0) {
            RandomSource random = minecraft.level.getRandom();
            emitMote(minecraft, random, origin);
            for (BlockPos pos : blocks) emitMote(minecraft, random, pos);
        }
    }

    private static void emitMote(Minecraft minecraft, RandomSource random, BlockPos pos) {
        double x = pos.getX() + 0.5 + (random.nextDouble() - 0.5) * 1.1;
        double y = pos.getY() + 0.5 + (random.nextDouble() - 0.5) * 1.1;
        double z = pos.getZ() + 0.5 + (random.nextDouble() - 0.5) * 1.1;
        minecraft.level.addParticle(ParticleTypes.REVERSE_PORTAL, x, y, z, 0.0, 0.01, 0.0);
    }

    private static void clearPreview() {
        previewOrigin = null;
        previewBlocks = List.of();
    }

    // ---- Shape selector -------------------------------------------------------------------------------------

    /**
     * The two lines drawn under the crosshair while the key is held: the chosen shape between scroll arrows, then one
     * pip per shape (filled = chosen, hollow = unlocked, dot = locked) and the block count. Empty when hidden.
     */
    public static List<Component> hudLines() {
        Minecraft minecraft = Minecraft.getInstance();
        int level = heldLevel(minecraft);
        if (level <= 0 || !keyHeld(minecraft)) return List.of();
        VeinShape current = VeinShape.effective(selected, level);

        Component name = Component.translatable(current.translationKey()).withStyle(ChatFormatting.LIGHT_PURPLE);
        MutableComponent title = VeinShape.unlocked(level).size() > 1
                ? Component.literal("‹ ").withStyle(ChatFormatting.DARK_PURPLE).append(name)
                        .append(Component.literal(" ›").withStyle(ChatFormatting.DARK_PURPLE))
                : name.copy();

        MutableComponent pips = Component.empty();
        for (VeinShape shape : VeinShape.values()) {
            if (shape == current) {
                pips.append(Component.literal("●").withStyle(ChatFormatting.LIGHT_PURPLE));
            } else if (shape.isUnlocked(level)) {
                pips.append(Component.literal("○").withStyle(ChatFormatting.DARK_PURPLE));
            } else {
                pips.append(Component.literal("·").withStyle(ChatFormatting.DARK_GRAY));
            }
        }
        int count = previewOrigin == null ? 0 : previewBlocks.size() + 1;
        pips.append(Component.literal("  ")).append(Component.translatable(HUD + "count", count).withStyle(ChatFormatting.GRAY));
        return List.of(title, pips);
    }
}
